# Generated by Django 5.2.3 on 2025-07-20 10:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content',
            field=models.TextField(default='No content available', validators=[django.core.validators.MinLengthValidator(10)]),
            preserve_default=False,
        ),
    ]
