# Generated by Django 5.2.3 on 2025-07-20 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_article_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='replay_to',
            new_name='reply_to',
        ),
    ]
