# Generated by Django 5.2.3 on 2025-07-21 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_replay_to_comment_reply_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='was_here_before',
            field=models.BooleanField(default=False),
        ),
    ]
