# Generated by Django 5.2.3 on 2025-07-21 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_userprofile_was_here_before'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='was_here_before',
        ),
    ]
